// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXT_1IH7MjImV0VUAh7vct-QEbx9CbOk',
    appId: '1:680149849612:web:08d4b28282d153afc48029',
    messagingSenderId: '680149849612',
    projectId: 'web-novel-app',
    authDomain: 'web-novel-app.firebaseapp.com',
    storageBucket: 'web-novel-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQombm13fVbYEvHIlnPnvPzgcf_QaSQ8',
    appId: '1:680149849612:android:5686abe4d0bf823dc48029',
    messagingSenderId: '680149849612',
    projectId: 'web-novel-app',
    storageBucket: 'web-novel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0N8Rd5XMw0rCEhs--tEnHwJdHyIBOsIo',
    appId: '1:680149849612:ios:7f6369ba68eda460c48029',
    messagingSenderId: '680149849612',
    projectId: 'web-novel-app',
    storageBucket: 'web-novel-app.appspot.com',
    iosClientId: '680149849612-7e6iige8oeedptcu8qv11k105qimh617.apps.googleusercontent.com',
    iosBundleId: 'com.example.webNovelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0N8Rd5XMw0rCEhs--tEnHwJdHyIBOsIo',
    appId: '1:680149849612:ios:3d639805dbd0d3a8c48029',
    messagingSenderId: '680149849612',
    projectId: 'web-novel-app',
    storageBucket: 'web-novel-app.appspot.com',
    iosClientId: '680149849612-7pv31lpp9gk17615qnt3ij6105mvpdml.apps.googleusercontent.com',
    iosBundleId: 'com.example.webNovelApp.RunnerTests',
  );
}
