class NovelExceptionCantGetNovels implements Exception{}
class NovelExceptionGeneric implements Exception{}
class NovelExceptionFileIsMessing implements Exception{}
class NovelExceptionCantGetGifts implements Exception{}
class NovelExceptionCantGetPower implements Exception{}
class NovelExceptionCantGetChapters implements Exception{}
class NovelExceptionCantUnLockChapter implements Exception{}
class NovelExceptionCantGetReviews implements Exception{}
class NovelExceptionCantGetReplies implements Exception{}
class NovelExceptionCantGetChapterContent implements Exception{}
class NovelExceptionCantGetChapterComment implements Exception{}
class NovelExceptionCantGetTextComment implements Exception{}
class NovelExceptionCantAddComment implements Exception{}